### ISSUE TITLE
Fleet management app testing - issues

### ISSUE THREAD

**Issue by PawanMeh** [dalwadani/fleet_management#1]
1) Seeing 2 set up screens and cryptic keys on list views
![screen shot 2016-08-01 at 6 41 30 pm](https://cloud.githubusercontent.com/assets/20460498/17295196/9d07b19c-5818-11e6-9ef0-092239493a40.png)
![screen shot 2016-08-01 at 6 42 26 pm](https://cloud.githubusercontent.com/assets/20460498/17295213/ad0012e2-5818-11e6-8268-30c8850b93ac.png)
2) Getting error when submitting 
: Please check your server logs or contact tech support.
Traceback (most recent call last):
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 660, in submit
    self._submit()
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 649, in _submit
    self.save()
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 242, in save
    return self._save(_args, *_kwargs)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 286, in _save
    self.run_post_save_methods()
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 708, in run_post_save_methods
    self.run_method("on_submit")
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, _args, *_kwargs)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, _args, *_kwargs)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, _args, *_kwargs))
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in 
    fn = lambda self, _args, *_kwargs: getattr(self, method)(_args, *_kwargs)
  File "/Users/pawan/frappe-bench/apps/fleet_management/fleet_management/fleet_management/doctype/vehicle_odometer_log/vehicle_odometer_log.py", line 15, in on_submit
    if (self.reading_time >= last_reading[0].reading_time):
TypeError: can't compare datetime.datetime to unicode

Traceback (most recent call last):
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, *_frappe.form_dict)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/**init**.py", line 876, in call
    return fn(_args, *_newargs)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 660, in submit
    self._submit()
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 649, in _submit
    self.save()
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 242, in save
    return self._save(_args, *_kwargs)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 286, in _save
    self.run_post_save_methods()
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 708, in run_post_save_methods
    self.run_method("on_submit")
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, *_kwargs)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, _args, *_kwargs)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, _args, *_kwargs))
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in 
    fn = lambda self, _args, *_kwargs: getattr(self, method)(_args, *_kwargs)
  File "/Users/pawan/frappe-bench/apps/fleet_management/fleet_management/fleet_management/doctype/vehicle_odometer_log/vehicle_odometer_log.py", line 15, in on_submit
    if (self.reading_time >= last_reading[0].reading_time):
TypeError: can't compare datetime.datetime to unicode
3) Odometer reading in a new log can be less than previous reading

**Comment by PawanMeh** [comment]
Created issue #6171 to create new Fleet Management Module
